services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_URI=${MONGO_URI}  # Connect directly to MongoDB Atlas
      - MONGO_DBNAME=${MONGO_DBNAME}
    networks:
      - dockership_network

volumes:
  mongodb_data:
    driver: local

networks:
  dockership_network:
    driver: bridge
